"""Add subtotal and delivery_fee to Order

Revision ID: 20e855624dbd
Revises: ba8f26c52ec5
Create Date: 2025-09-24 10:35:20.264337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e855624dbd'
down_revision = 'ba8f26c52ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.Float(), nullable=True))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_item_menu'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_order_item_menu'), 'menu', ['menu_id'], ['menu_id'], ondelete='CASCADE')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('subtotal')

    # ### end Alembic commands ###
