"""Add PromoCode model

Revision ID: ba8f26c52ec5
Revises: cf58cf8717e1
Create Date: 2025-09-20 10:07:10.256152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8f26c52ec5'
down_revision = 'cf58cf8717e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_code')
    # ### end Alembic commands ###
