"""Add delivery_address, promo_code, discount to Order

Revision ID: cf58cf8717e1
Revises: c323777155ff
Create Date: 2025-08-23 09:31:10.278778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf58cf8717e1'
down_revision = 'c323777155ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('promo_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('promo_code')
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###
